// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jsonwebtoken from "jsonwebtoken";

function sign(payload, secret, options) {
  return new Promise((function (resolve, param) {
                Jsonwebtoken.sign(payload, secret, options, (function (err, token) {
                        if (!(err === null || err === undefined)) {
                          return resolve({
                                      TAG: "Error",
                                      _0: err
                                    });
                        }
                        err === null;
                        if (!(token === null || token === undefined)) {
                          return resolve({
                                      TAG: "Ok",
                                      _0: token
                                    });
                        }
                        if (token === null) {
                          throw {
                                RE_EXN_ID: "Assert_failure",
                                _1: [
                                  "Jwt.res",
                                  12,
                                  13
                                ],
                                Error: new Error()
                              };
                        }
                        throw {
                              RE_EXN_ID: "Assert_failure",
                              _1: [
                                "Jwt.res",
                                12,
                                13
                              ],
                              Error: new Error()
                            };
                      }));
              }));
}

export {
  sign ,
}
/* jsonwebtoken Not a pure module */
