// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jsonwebtoken from "jsonwebtoken";

function sign(payload, secret, options) {
  return new Promise((function (resolve, param) {
                Jsonwebtoken.sign(payload, secret, options, (function (err, token) {
                        if (err !== undefined) {
                          return resolve({
                                      TAG: "Error",
                                      _0: err
                                    });
                        }
                        if (token !== undefined) {
                          return resolve({
                                      TAG: "Ok",
                                      _0: token
                                    });
                        }
                        throw {
                              RE_EXN_ID: "Assert_failure",
                              _1: [
                                "Jwt.res",
                                11,
                                13
                              ],
                              Error: new Error()
                            };
                      }));
              }));
}

export {
  sign ,
}
/* jsonwebtoken Not a pure module */
