// Generated by ReScript, PLEASE EDIT WITH CARE


var Cookies = {};

var $$Headers = {
  Cookies: Cookies
};

var Link = {};

var Router = {};

var $$Navigation = {
  Router: Router
};

export {
  $$Headers ,
  Link ,
  $$Navigation ,
}
/* No side effect */
