// Generated by ReScript, PLEASE EDIT WITH CARE


import { types } from 'pg';
types.setTypeParser(types.builtins.INT8, v => parseInt(v, 10));
types.setTypeParser(types.builtins.DATE, v => v);
;

var Pool = {};

export {
  Pool ,
}
/*  Not a pure module */
