'use client'
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Auth from "../Auth.res.js";
import Link from "next/link";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function authUrl(clientId, from) {
  var state = encodeURIComponent(from);
  var host = window.location.origin;
  var redirectUri = encodeURIComponent(host + "/login/naver/callback");
  return "https://nid.naver.com/oauth2.0/authorize?response_type=code&client_id=" + clientId + "&redirect_uri=" + redirectUri + "&state=" + state;
}

function Pages_Login_Impl(props) {
  var auth = Auth.useSync();
  var from = Core__Option.getOr(props.searchParams.from, "/");
  var from$1 = from.startsWith("/") ? from : "/";
  if (typeof auth !== "object") {
    if (auth === "Loading") {
      return JsxRuntime.jsx("main", {
                  children: "로딩중..."
                });
    } else {
      return JsxRuntime.jsxs("main", {
                  children: [
                    JsxRuntime.jsx("h1", {
                          children: "로그인",
                          className: "text-2xl font-bold"
                        }),
                    JsxRuntime.jsx("p", {
                          children: "네이버로 로그인하여 일지를 쓰고 반응을 남겨보세요"
                        }),
                    JsxRuntime.jsx("a", {
                          children: JsxRuntime.jsx("img", {
                                alt: "네이버로 로그인",
                                height: "60",
                                src: "/img/naverLogin.png",
                                width: "225"
                              }),
                          href: authUrl(props.clientId, from$1)
                        })
                  ]
                });
    }
  } else {
    return JsxRuntime.jsxs("main", {
                children: [
                  JsxRuntime.jsx("p", {
                        children: "이미 로그인되어 있습니다"
                      }),
                  JsxRuntime.jsx(Link, {
                        href: from$1,
                        children: "돌아가기"
                      })
                ]
              });
  }
}

var make = Pages_Login_Impl;

export {
  authUrl ,
  make ,
}
/* Auth Not a pure module */
