// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

async function $$default(param) {
  return JsxRuntime.jsx("article", {
              children: JsxRuntime.jsx("h1", {
                    children: "환영합니다"
                  })
            });
}

var Pages_Main$default = $$default;

var $$default$1 = Pages_Main$default;

export {
  $$default$1 as default,
}
/* react/jsx-runtime Not a pure module */
