'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Auth from "../Auth.res.js";
import * as Actions from "../Actions.res.js";
import Link from "next/link";
import * as $$Navigation from "next/navigation";
import * as JsxRuntime from "react/jsx-runtime";

function Pages_HeaderLayout_AuthMenu$Container(props) {
  return JsxRuntime.jsx("menu", {
              children: props.children,
              className: "flex items-center flex-wrap min-w-0"
            });
}

var Container = {
  make: Pages_HeaderLayout_AuthMenu$Container
};

function Pages_HeaderLayout_AuthMenu$Item(props) {
  return JsxRuntime.jsx("li", {
              children: props.children,
              className: "before:content-['·'] first:before:content-none before:mx-1 min-w-0 flex"
            });
}

var Item = {
  make: Pages_HeaderLayout_AuthMenu$Item
};

function Pages_HeaderLayout_AuthMenu(props) {
  var auth = Auth.useSync();
  var router = $$Navigation.useRouter();
  var handleLogin = function (e) {
    e.preventDefault();
    var from = encodeURIComponent((window.location.pathname + window.location.search + window.location.hash));
    router.push("/login?from=" + from);
  };
  var handleLogout = function (e) {
    e.preventDefault();
    Actions.logout();
    Auth.update("Anon");
  };
  if (typeof auth !== "object") {
    if (auth === "Loading") {
      return JsxRuntime.jsx(Pages_HeaderLayout_AuthMenu$Container, {
                  children: JsxRuntime.jsx(Pages_HeaderLayout_AuthMenu$Item, {
                        children: "사용자 확인중..."
                      })
                });
    } else {
      return JsxRuntime.jsx(Pages_HeaderLayout_AuthMenu$Container, {
                  children: JsxRuntime.jsx(Pages_HeaderLayout_AuthMenu$Item, {
                        children: JsxRuntime.jsx("a", {
                              children: "로그인",
                              href: "/login",
                              onClick: handleLogin
                            })
                      })
                });
    }
  } else {
    return JsxRuntime.jsxs(Pages_HeaderLayout_AuthMenu$Container, {
                children: [
                  JsxRuntime.jsxs(Pages_HeaderLayout_AuthMenu$Item, {
                        children: [
                          JsxRuntime.jsx("div", {
                                children: auth._0.profile.name,
                                className: "overflow-hidden text-ellipsis whitespace-nowrap min-w-0"
                              }),
                          JsxRuntime.jsx("div", {
                                children: "님 환영합니다",
                                className: "whitespace-nowrap"
                              })
                        ]
                      }),
                  JsxRuntime.jsx(Pages_HeaderLayout_AuthMenu$Item, {
                        children: JsxRuntime.jsx(Link, {
                              href: "/drafts",
                              children: "일지 쓰기"
                            })
                      }),
                  JsxRuntime.jsx(Pages_HeaderLayout_AuthMenu$Item, {
                        children: JsxRuntime.jsx("a", {
                              children: "로그아웃",
                              href: "/logout",
                              onClick: handleLogout
                            })
                      })
                ]
              });
  }
}

var make = Pages_HeaderLayout_AuthMenu;

export {
  Container ,
  Item ,
  make ,
}
/* Auth Not a pure module */
