'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icons from "../Icons.res.js";
import * as React from "react";
import Link from "next/link";
import * as JsxRuntime from "react/jsx-runtime";

function Pages_HeaderLayout_NavMenu$Button(props) {
  return JsxRuntime.jsx("button", {
              children: props.children,
              className: "bg-white rounded-full border my-2 size-12 md:hidden",
              onClick: props.onClick
            });
}

var Button = {
  make: Pages_HeaderLayout_NavMenu$Button
};

function Pages_HeaderLayout_NavMenu(props) {
  var match = React.useState(function () {
        return false;
      });
  var setIsOpen = match[1];
  var isOpen = match[0];
  var handleToggle = function (e) {
    e.stopPropagation();
    setIsOpen(function (prev) {
          return !prev;
        });
  };
  var handleGoToTop = function (param) {
    window.scrollTo({
          left: 0.0,
          top: 0.0,
          behavior: "smooth"
        });
  };
  var menus = [
    [
      "소개",
      "/"
    ],
    [
      "모든 일지",
      "/articles"
    ]
  ];
  return JsxRuntime.jsxs("nav", {
              children: [
                JsxRuntime.jsx("div", {
                      className: "fixed opacity-75 bg-white inset-0 -z-10 transition-opacity md:hidden" + (
                        isOpen ? "" : " hidden"
                      ),
                      onClick: (function (param) {
                          setIsOpen(function (param) {
                                return false;
                              });
                        })
                    }),
                JsxRuntime.jsx("ul", {
                      children: menus.map(function (param) {
                            var href = param[1];
                            return JsxRuntime.jsx("li", {
                                        children: JsxRuntime.jsx(Link, {
                                              href: href,
                                              children: param[0]
                                            }),
                                        onClick: (function (param) {
                                            setIsOpen(function (param) {
                                                  return false;
                                                });
                                          })
                                      }, href);
                          }),
                      className: "absolute right-0 bottom-full whitespace-nowrap text-right md:static md:inset-auto md:block md:text-left" + (
                        isOpen ? "" : " hidden"
                      )
                    }),
                JsxRuntime.jsx(Pages_HeaderLayout_NavMenu$Button, {
                      children: isOpen ? JsxRuntime.jsx(Icons.Close.make, {}) : JsxRuntime.jsx(Icons.Menu.make, {}),
                      onClick: handleToggle
                    }),
                JsxRuntime.jsx(Pages_HeaderLayout_NavMenu$Button, {
                      children: JsxRuntime.jsx(Icons.GoToTop.make, {}),
                      onClick: handleGoToTop
                    })
              ],
              className: "fixed bottom-0 right-0 m-8 flex flex-col text-xl md:static md:inset-auto md:m-0 md:text-base md:bg-neutral-200 md:p-4"
            });
}

var make = Pages_HeaderLayout_NavMenu;

export {
  Button ,
  make ,
}
/* Icons Not a pure module */
