// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icons from "../Icons.res.js";
import Link from "next/link";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Components_Stat from "./Components_Stat.res.js";
import * as Components_Time from "./Components_Time.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function Components_ArticleList(props) {
  return JsxRuntime.jsx("ul", {
              children: props.children,
              className: "border-t"
            });
}

function Components_ArticleList$ItemBase(props) {
  var __icon = props.icon;
  var icon = __icon !== undefined ? Caml_option.valFromOption(__icon) : null;
  return JsxRuntime.jsxs("li", {
              children: [
                icon,
                JsxRuntime.jsx("hr", {
                      className: "border-0 w-1"
                    }),
                props.children
              ],
              className: "border-b p-1 flex items-center flex-wrap"
            });
}

var ItemBase = {
  make: Components_ArticleList$ItemBase
};

function Components_ArticleList$Placeholder(props) {
  var __icon = props.icon;
  var icon = __icon !== undefined ? Caml_option.valFromOption(__icon) : null;
  return JsxRuntime.jsx(Components_ArticleList$ItemBase, {
              children: JsxRuntime.jsx("p", {
                    children: props.children,
                    className: "text-center text-neutral-500"
                  }),
              icon: Caml_option.some(icon)
            });
}

var Placeholder = {
  make: Components_ArticleList$Placeholder
};

function Components_ArticleList$Item(props) {
  var __icon = props.icon;
  var item = props.item;
  var icon = __icon !== undefined ? Caml_option.valFromOption(__icon) : null;
  return JsxRuntime.jsxs(Components_ArticleList$ItemBase, {
              children: [
                JsxRuntime.jsxs("p", {
                      children: [
                        JsxRuntime.jsx(Link, {
                              href: "/articles/" + item.id.toString(),
                              children: item.title,
                              className: "mr-1"
                            }),
                        JsxRuntime.jsxs("span", {
                              children: [
                                JsxRuntime.jsx(Components_Stat.make, {
                                      icon: JsxRuntime.jsx(Icons.$$Comment.make, {}),
                                      count: item.commentsCount
                                    }),
                                JsxRuntime.jsx(Components_Stat.make, {
                                      icon: JsxRuntime.jsx(Icons.Visibility.make, {}),
                                      count: item.viewsCount
                                    }),
                                JsxRuntime.jsx(Components_Stat.make, {
                                      icon: JsxRuntime.jsx(Icons.Favorite.make, {}),
                                      count: item.likesCount
                                    })
                              ],
                              className: "text-neutral-500"
                            })
                      ]
                    }),
                JsxRuntime.jsxs("p", {
                      children: [
                        item.authorName + ", ",
                        JsxRuntime.jsx(Components_Time.make, {
                              children: item.publishedAt
                            })
                      ],
                      className: "mr-1 text-neutral-500 text-sm whitespace-nowrap min-w-fit flex-1 text-right"
                    })
              ],
              icon: Caml_option.some(icon)
            });
}

var Item = {
  make: Components_ArticleList$Item
};

var make = Components_ArticleList;

export {
  make ,
  ItemBase ,
  Placeholder ,
  Item ,
}
/* Icons Not a pure module */
