// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Components_Stat(props) {
  var __size = props.size;
  var count = props.count;
  var size = __size !== undefined ? __size : "size-5";
  if (count > 0) {
    return JsxRuntime.jsxs("span", {
                children: [
                  JsxRuntime.jsx("img", {
                        className: "inline " + size,
                        alt: props.alt,
                        src: props.icon
                      }),
                  count.toString()
                ],
                className: "mr-1 text-gray-500 whitespace-nowrap min-w-fit inline-block"
              });
  } else {
    return null;
  }
}

var make = Components_Stat;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
