// Generated by ReScript, PLEASE EDIT WITH CARE

import Link from "next/link";
import * as Components_Stat from "./Components_Stat.res.js";
import * as Components_Time from "./Components_Time.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function Components_ArticleList(props) {
  return JsxRuntime.jsx("ul", {
              children: props.children,
              className: "border-t"
            });
}

function Components_ArticleList$Item(props) {
  var item = props.item;
  return JsxRuntime.jsxs("li", {
              children: [
                JsxRuntime.jsxs("p", {
                      children: [
                        JsxRuntime.jsx(Link, {
                              href: "/articles/" + item.id.toString(),
                              children: item.title,
                              className: "mr-1"
                            }),
                        JsxRuntime.jsx(Components_Stat.make, {
                              icon: "/icons/comment.svg",
                              alt: "댓글",
                              count: item.commentsCount
                            }),
                        JsxRuntime.jsx(Components_Stat.make, {
                              icon: "/icons/visibility.svg",
                              alt: "조회수",
                              count: item.viewsCount
                            }),
                        JsxRuntime.jsx(Components_Stat.make, {
                              icon: "/icons/favorite.svg",
                              alt: "좋아요",
                              count: item.likesCount
                            })
                      ]
                    }),
                JsxRuntime.jsxs("p", {
                      children: [
                        item.authorName + ",",
                        JsxRuntime.jsx(Components_Time.make, {
                              children: item.publishedAt
                            })
                      ],
                      className: "mr-1 text-gray-500 text-sm whitespace-nowrap min-w-fit flex-1 text-right"
                    })
              ],
              className: "border-b p-1 flex items-center flex-wrap"
            });
}

var Item = {
  make: Components_ArticleList$Item
};

var make = Components_ArticleList;

export {
  make ,
  Item ,
}
/* next/link Not a pure module */
