// Generated by ReScript, PLEASE EDIT WITH CARE

import Link from "next/link";
import * as Components_Time from "./Components_Time.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function Components_ArticleList$Container(props) {
  return JsxRuntime.jsx("ul", {
              children: props.children,
              className: "border-t"
            });
}

var Container = {
  make: Components_ArticleList$Container
};

function Components_ArticleList$Item(props) {
  var item = props.item;
  return JsxRuntime.jsxs("li", {
              children: [
                JsxRuntime.jsx(Link, {
                      href: "/articles/" + item.id.toString(),
                      children: item.title,
                      className: "flex-1"
                    }),
                JsxRuntime.jsx("p", {
                      children: item.authorName + ",",
                      className: "mr-1"
                    }),
                JsxRuntime.jsx(Components_Time.make, {
                      children: item.publishedAt
                    })
              ],
              className: "border-b p-1 flex"
            });
}

var Item = {
  make: Components_ArticleList$Item
};

export {
  Container ,
  Item ,
}
/* next/link Not a pure module */
