// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

var databaseUrl = Core__Option.getExn(process.env.DATABASE_URL, undefined, "DATABASE_URL environment variable is not set");

var redisUrl = Core__Option.getExn(process.env.REDIS_URL, undefined, "REDIS_URL environment variable is not set");

var jwtSecret = Core__Option.getExn(process.env.JWT_SECRET, undefined, "JWT_SECRET environment variable is not set");

export {
  databaseUrl ,
  redisUrl ,
  jwtSecret ,
}
/* databaseUrl Not a pure module */
