// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Make(S) {
  var Icons$Make = function (props) {
    var __className = props.className;
    var className = __className !== undefined ? __className : "";
    return JsxRuntime.jsx("span", {
                children: String.fromCharCode(S.code),
                className: "material-symbols-outlined " + className
              });
  };
  return {
          make: Icons$Make
        };
}

function Icons$Make(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsx("span", {
              children: String.fromCharCode(57529),
              className: "material-symbols-outlined " + className
            });
}

var $$Comment = {
  make: Icons$Make
};

function Icons$Make$1(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsx("span", {
              children: String.fromCharCode(59636),
              className: "material-symbols-outlined " + className
            });
}

var Visibility = {
  make: Icons$Make$1
};

function Icons$Make$2(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsx("span", {
              children: String.fromCharCode(59517),
              className: "material-symbols-outlined " + className
            });
}

var Favorite = {
  make: Icons$Make$2
};

function Icons$Make$3(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsx("span", {
              children: String.fromCharCode(58134),
              className: "material-symbols-outlined " + className
            });
}

var ArrowUp = {
  make: Icons$Make$3
};

function Icons$Make$4(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsx("span", {
              children: String.fromCharCode(58131),
              className: "material-symbols-outlined " + className
            });
}

var ArrowDown = {
  make: Icons$Make$4
};

function Icons$Make$5(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsx("span", {
              children: String.fromCharCode(58133),
              className: "material-symbols-outlined " + className
            });
}

var ArrowRight = {
  make: Icons$Make$5
};

function Icons$Make$6(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsx("span", {
              children: String.fromCharCode(58834),
              className: "material-symbols-outlined " + className
            });
}

var Menu = {
  make: Icons$Make$6
};

function Icons$Make$7(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsx("span", {
              children: String.fromCharCode(58829),
              className: "material-symbols-outlined " + className
            });
}

var Close = {
  make: Icons$Make$7
};

function Icons$Make$8(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsx("span", {
              children: String.fromCharCode(58840),
              className: "material-symbols-outlined " + className
            });
}

var GoToTop = {
  make: Icons$Make$8
};

function Icons$Make$9(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsx("span", {
              children: String.fromCharCode(58835),
              className: "material-symbols-outlined " + className
            });
}

var More = {
  make: Icons$Make$9
};

function Icons$Make$10(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsx("span", {
              children: String.fromCharCode(59506),
              className: "material-symbols-outlined " + className
            });
}

var Delete = {
  make: Icons$Make$10
};

export {
  Make ,
  $$Comment ,
  Visibility ,
  Favorite ,
  ArrowUp ,
  ArrowDown ,
  ArrowRight ,
  Menu ,
  Close ,
  GoToTop ,
  More ,
  Delete ,
}
/* react/jsx-runtime Not a pure module */
