'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Auth from "./Auth.res.mjs";
import * as React from "react";

function InitToken(props) {
  React.useInsertionEffect((function () {
          Auth.initToken();
        }), []);
  return null;
}

var make = InitToken;

export {
  make ,
}
/* Auth Not a pure module */
