'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as GlobalState from "./GlobalState.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function initial() {
  return Date.now();
}

var include = GlobalState.Make({
      initial: initial
    });

var update = include.update;

var addHook = include.addHook;

var timeout = {
  contents: undefined
};

addHook(function (param) {
      Core__Option.map(timeout.contents, (function (prim) {
              clearTimeout(prim);
            }));
      timeout.contents = Caml_option.some(setTimeout((function () {
                  update(Date.now());
                }), 60000));
    });

update(Date.now());

var useSync = include.useSync;

export {
  useSync ,
  update ,
  addHook ,
  timeout ,
}
/* include Not a pure module */
