'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

var state = {
  contents: Date.now()
};

var listeners = new Set();

function use() {
  return React.useSyncExternalStore((function (listener) {
                listeners.add(listener);
                return function () {
                  listeners.delete(listener);
                };
              }), (function () {
                return state.contents;
              }), (function () {
                return Date.now();
              }));
}

var timeout = {
  contents: undefined
};

function update(newState) {
  state.contents = newState;
  Core__Option.map(timeout.contents, (function (prim) {
          clearTimeout(prim);
        }));
  timeout.contents = Caml_option.some(setTimeout((function () {
              update(Date.now());
            }), 60000));
  listeners.forEach(function (listener) {
        listener();
      });
}

update(Date.now());

export {
  state ,
  listeners ,
  use ,
  timeout ,
  update ,
}
/* state Not a pure module */
