// Generated by ReScript, PLEASE EDIT WITH CARE

import Link from "next/link";
import * as JsxRuntime from "react/jsx-runtime";

function Pages_HeaderLayout$default(props) {
  return JsxRuntime.jsxs("main", {
              children: [
                JsxRuntime.jsx("header", {
                      children: JsxRuntime.jsx(Link, {
                            href: "/",
                            children: "왼손잡이해방연대 아지트",
                            className: "text-2xl font-bold"
                          }),
                      className: "flex justify-between bg-gray-200 my-4 p-4"
                    }),
                props.children
              ],
              className: "mx-auto flex flex-col max-w-screen-lg p-4"
            });
}

var $$default = Pages_HeaderLayout$default;

export {
  $$default as default,
}
/* next/link Not a pure module */
