// Generated by ReScript, PLEASE EDIT WITH CARE

import * as InitToken from "./InitToken.res.js";
import * as JsxRuntime from "react/jsx-runtime";

var metadata = {
  title: {
    template: "%s | 왼손잡이해방연대 아지트",
    default: "왼손잡이해방연대 아지트"
  },
  description: "오른손도 자주 씁니다"
};

function Pages_RootLayout$default(props) {
  return JsxRuntime.jsxs("html", {
              children: [
                JsxRuntime.jsx("head", {
                      children: JsxRuntime.jsx("link", {
                            href: "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0..1,0",
                            rel: "stylesheet"
                          })
                    }),
                JsxRuntime.jsx("body", {
                      children: props.children
                    }),
                JsxRuntime.jsx(InitToken.make, {})
              ],
              lang: "ko"
            });
}

var $$default = Pages_RootLayout$default;

export {
  metadata ,
  $$default as default,
}
/* InitToken Not a pure module */
