'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Auth from "./Auth.res.js";
import Link from "next/link";
import * as $$Navigation from "next/navigation";
import * as JsxRuntime from "react/jsx-runtime";

function Pages_HeaderLayout_AuthMenu$Container(props) {
  return JsxRuntime.jsx("menu", {
              children: props.children,
              className: "flex space-x-4 items-center"
            });
}

var Container = {
  make: Pages_HeaderLayout_AuthMenu$Container
};

function Pages_HeaderLayout_AuthMenu(props) {
  var auth = Auth.useSync();
  var router = $$Navigation.useRouter();
  var handleLogin = function (e) {
    e.preventDefault();
    var from = encodeURIComponent((window.location.pathname + window.location.search + window.location.hash));
    router.push("/login?from=" + from);
  };
  if (typeof auth !== "object") {
    if (auth === "Loading") {
      return JsxRuntime.jsx(Pages_HeaderLayout_AuthMenu$Container, {
                  children: "사용자 확인중..."
                });
    } else {
      return JsxRuntime.jsx(Pages_HeaderLayout_AuthMenu$Container, {
                  children: JsxRuntime.jsx("li", {
                        children: JsxRuntime.jsx("a", {
                              children: "로그인",
                              href: "/login",
                              onClick: handleLogin
                            })
                      })
                });
    }
  } else {
    return JsxRuntime.jsxs(Pages_HeaderLayout_AuthMenu$Container, {
                children: [
                  JsxRuntime.jsx("li", {
                        children: auth._0.profile.name + "님 환영합니다"
                      }),
                  JsxRuntime.jsx("li", {
                        children: JsxRuntime.jsx(Link, {
                              href: "/drafts",
                              children: "일지 쓰기"
                            })
                      }),
                  JsxRuntime.jsx("li", {
                        children: JsxRuntime.jsx(Link, {
                              href: "/logout",
                              children: "로그아웃"
                            })
                      })
                ]
              });
  }
}

var make = Pages_HeaderLayout_AuthMenu;

export {
  Container ,
  make ,
}
/* Auth Not a pure module */
