// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Db from "./Db.res.mjs";
import * as Pages_Main__sql from "./Pages_Main__sql.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

async function $$default(param) {
  var articles = await Db.query(Pages_Main__sql.Query1.many, undefined);
  if (articles.TAG === "Ok") {
    return JsxRuntime.jsx("main", {
                children: articles._0.map(function (article) {
                      return JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("h2", {
                                          children: article.title
                                        }),
                                    JsxRuntime.jsx("p", {
                                          children: article.author_name
                                        }),
                                    JsxRuntime.jsx("p", {
                                          children: article.first_published_at.toString()
                                        }),
                                    JsxRuntime.jsx("p", {
                                          children: article.comments_count.toString()
                                        }),
                                    JsxRuntime.jsx("p", {
                                          children: article.views_count.toString()
                                        }),
                                    JsxRuntime.jsx("p", {
                                          children: article.likes_count.toString()
                                        })
                                  ]
                                }, article.id.toString());
                    })
              });
  } else {
    return JsxRuntime.jsx("main", {
                children: "error"
              });
  }
}

var Pages_Main$default = $$default;

var $$default$1 = Pages_Main$default;

export {
  $$default$1 as default,
}
/* Db Not a pure module */
