'use client'
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function Pages_RootError$default(props) {
  var reset = props.reset;
  var error = props.error;
  return JsxRuntime.jsxs("main", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "알 수 없는 오류!"
                    }),
                JsxRuntime.jsx("button", {
                      children: "다시 시도",
                      onClick: (function (param) {
                          reset();
                        })
                    }),
                JsxRuntime.jsx("p", {
                      children: "오류가 계속되면 아래 내용을 관리자에게 문의하세요"
                    }),
                JsxRuntime.jsx("p", {
                      children: Core__Option.getOr(error.message, "")
                    }),
                JsxRuntime.jsx("p", {
                      children: "digest: " + Core__Option.getOr(error.digest, "")
                    })
              ]
            });
}

var $$default = Pages_RootError$default;

export {
  $$default as default,
}
/* react/jsx-runtime Not a pure module */
